server:
 port: 8090

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springjdbc
    username: 'root'
    password: 'root'
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      

  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      